version: "2"
services:
  pdns:
    image: secns/pdns
    ports:
    - "53:5353"
    ports:
    - "8080:80"
    environment:
    - PDNS_ALLOW_AXFR_IPS=127.0.0.1
    - PDNS_DISTRIBUTOR_THREADS=3
    - PDNS_CACHE_TTL=20
    - PDNS_RECURSIVE_CACHE_TTL=10
    - DB_ENV_MYSQL_ROOT_PASSWORD=changeme
  db:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=changeme
  recursor:
    image: tcely/powerdns-recursor'
    restart: 'unless-stopped'
    command: ["--disable-syslog=yes", "--log-timestamp=no", "--local-address=0.0.0.0", "--setuid=pdns-recursor", "--setgid=pdns-recursor"]
    volumes:
      - ./pdns-recursor.conf:/etc/pdns-recursor/recursor.conf:ro
    ports:
      - "53:53"
      - "53:53/udp"
